export const KEYBOARD_LAYOUT = [
  "{esc} F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12",
  "` 1 2 3 4 5 6 7 8 9 0 - = {bksp}",
  "{tab} q w e r t y u i o p [ ] \\",
  "{lock} a s d f g h j k l ; ' {enter}",
  "{shiftl} z x c v b n m , . / {shiftr} ↑",
  "{ctrll} {altl} {cmdl} {space} {cmdr} {altr} ← ↓ →",
];

export const KEYBOARD_LAYOUT_TO_KEY_CODE: Record<string, string> = {
  "{esc}": "Escape",
  F1: "F1",
  F2: "F2",
  F3: "F3",
  F4: "F4",
  F5: "F5",
  F6: "F6",
  F7: "F7",
  F8: "F8",
  F9: "F9",
  F10: "F10",
  F11: "F11",
  F12: "F12",
  "`": "Backquote",
  1: "Digit1",
  2: "Digit2",
  3: "Digit3",
  4: "Digit4",
  5: "Digit5",
  6: "Digit6",
  7: "Digit7",
  8: "Digit8",
  9: "Digit9",
  0: "Digit0",
  "-": "Minus",
  "=": "Equal",
  "{bksp}": "Backspace",
  "{tab}": "Tab",
  q: "KeyQ",
  w: "KeyW",
  e: "KeyE",
  r: "KeyR",
  t: "KeyT",
  y: "KeyY",
  u: "KeyU",
  i: "KeyI",
  o: "KeyO",
  p: "KeyP",
  "[": "BracketLeft",
  "]": "BracketRight",
  "\\": "Backslash",
  "{lock}": "CapsLock",
  a: "KeyA",
  s: "KeyS",
  d: "KeyD",
  f: "KeyF",
  g: "KeyG",
  h: "KeyH",
  j: "KeyJ",
  k: "KeyK",
  l: "KeyL",
  ";": "Semicolon",
  "'": "Quote",
  "{enter}": "Enter",
  "{shiftl}": "ShiftLeft",
  z: "KeyZ",
  x: "KeyX",
  c: "KeyC",
  v: "KeyV",
  b: "KeyB",
  n: "KeyN",
  m: "KeyM",
  ",": "Comma",
  ".": "Period",
  "/": "Slash",
  "{shiftr}": "ShiftRight",
  "↑": "ArrowUp",
  "{ctrll}": "ControlLeft",
  "{altl}": "AltLeft",
  "{cmdl}": "MetaLeft",
  "{space}": "Space",
  "{cmdr}": "MetaRight",
  "{altr}": "AltRight",
  "←": "ArrowLeft",
  "↓": "ArrowDown",
  "→": "ArrowRight",
};

export const KEYBOARD_DISPLAY_LABELS: Record<string, string> = {
  "{esc}": "Esc",
  "{bksp}": "Backspace",
  "{tab}": "Tab",
  "{lock}": "CapsLock",
  "{enter}": "Return",
  "{shiftl}": "Shift",
  "{shiftr}": "Shift",
  "{ctrll}": "Ctrl",
  "{altl}": "Alt",
  "{cmdl}": "Command",
  "{space}": "",
  "{cmdr}": "Command",
  "{altr}": "Alt",
};
